#pragma once
/*
    #version:1# (machine generated, don't edit!)

    Generated by sokol-shdc (https://github.com/floooh/sokol-tools)

    Cmdline:
        sokol-shdc --input src/shader/common.glsl --output src/shader/common.glsl.h --slang metal_macos --format=sokol_impl -r

    Overview:
    =========
*/
#if !defined(SOKOL_GFX_INCLUDED)
#error "Please include sokol_gfx.h before common.glsl.h"
#endif
#if !defined(SOKOL_SHDC_ALIGN)
#if defined(_MSC_VER)
#define SOKOL_SHDC_ALIGN(a) __declspec(align(a))
#else
#define SOKOL_SHDC_ALIGN(a) __attribute__((aligned(a)))
#endif
#endif
#if defined(SOKOL_SHDC_IMPL)
#endif // SOKOL_SHDC_IMPL