#include "defs.h"

ENUM_DEFINE(level_type, LT, ENUM_LEVEL_TYPE)
ENUM_DEFINE(plane_type, PLANE_TYPE, ENUM_PLANE_TYPE)
ENUM_DEFINE(side_segment, SIDE_SEGMENT, ENUM_SIDE_SEGMENT)
ENUM_DEFINE(entity_type, ENTITY_TYPE, ENUM_ENTITY_TYPE)
ENUM_DEFINE(decal_type, DECAL_TYPE, ENUM_DECAL_TYPE)
ENUM_DEFINE(sector_type, SECTOR_TYPE, ENUM_SECTOR_TYPE)
ENUM_DEFINE(plat_type_index, PLAT_TYPE, ENUM_PLAT_TYPE_INDEX)
ENUM_DEFINE(liquid_type_index, LIQUID_TYPE, ENUM_LIQUID_TYPE_INDEX)
ENUM_DEFINE(visopt, VISOPT, ENUM_VISOPT)
